apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
  strategy: {}
  template:
    spec:
      containers:
      - image: hello-node:1.0
        name: hello-node
        resources: {}
        imagePullPolicy: Never